version: "3.8"

volumes:
  umami-db-data:

services:
  umami:
    restart: always
    container_name: umami
    image: ghcr.io/umami-software/umami:postgresql-v2.8.0
    ports:
      - 127.0.0.1:4300:3000
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@umami_db:5432/${POSTGRES_DB}
      DATABASE_TYPE: postgresql
    depends_on:
      - umami_db

  umami_db:
    restart: always
    container_name: umami_db
    image: postgres:15.5-alpine3.18
    env_file:
      - .env
    volumes:
      - umami-db-data:/var/lib/postgresql/data
