global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

remote_write:
  - url: "grafana:3000"
    basic_auth:
      username: "admin"
      password: "$i&aY6XFcCV$#537"
