version: "3.8"

networks:
  my_links_internal:
    external: true

services:
  mylinks:
    restart: always
    container_name: mylinks
    image: sonny93/my-links:latest
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ../database/.env
      - .env
    networks:
      - my_links_internal
