version: "3"

volumes:
  db_vol:

services:
  npm_db:
    restart: always
    container_name: npm_db
    image: jc21/mariadb-aria:10.11.5
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  nginx:
    restart: always
    container_name: npm
    image: jc21/nginx-proxy-manager:2.10.4
    env_file:
      - .env
    environment:
      - DB_MYSQL_PORT=3306
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    network_mode: host # Host needed to discover all exposed containers
    depends_on:
      - npm_db
